[tool.poetry]
name = "mypkg"
version = "0.1.0"
description = ""
authors = ["Phillip Cloud <417981+cpcloud@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-autorefs = "^0.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
